### PR TITLE
feat: Added navigation icons for small screens

### LINKED ISSUE #106: [Feautre]: NavBar Element could have Icon corresponding to their title
**If navbar element will have icons corresponding to their title it will look good to human eyes and is easy to navigate** 

Screenshot (180)

**instead of just having anker tag**

we could have a li tag in li tag  we could have a icon and than  the anker tag with it

### PR DESCRIPTION
**Pull request by Ankush-Ladani**
## What does this PR do?
There were no icons in navBar when comes to small screen. So It was not looking good in terms of UI. So after this code changes , icons will be added with navItems.

Fixes #106

Before
image

After
image

## Type of change

- New feature (non-breaking change which adds functionality)

## How should this be tested?
- [x] Go To Home Page
- [x] Resize your screen to some amount until navItem will be replaced by one Icon
- [x] Tap on the icon
- [x] You will see same as above screenshot

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by TheMohit2003** [comment]
@Ankush-Ladani , nice one !! Can you change the gear icon to this :  
<br>
image

**Comment by TheMohit2003** [comment]
Can you add this as a login icon : 
image

**Comment by TheMohit2003** [comment]
@Ankush-Ladani , i am looking to merge this branch, can you quickly change those icons, that I recommended to you?

**Comment by Ankush-Ladani** [comment]
> @Ankush-Ladani , nice one !! Can you change the gear icon to this : image

But I have used icons from react-icons only. So can you please suggest me from their only?
Then it will be good for me.

**Comment by Ankush-Ladani** [comment]
> @Ankush-Ladani , i am looking to merge this branch, can you quickly change those icons, that I recommended to you?

I have Made the changes you can see.

**Pull request merged**
