### PR TITLE
feat: Update website with new colour, and make some components of website responsive

### LINKED ISSUE #156: [FEAT]: UI Changes and making Components responsive
**_Is your feature request related to a problem? Please describe._**
    This PR is related **responsive problem**. 

1. When screen gets smaller the testimonials text comes out of the box, and 
2. also with the intro page also losses it alignment when screen becomes smaller and smaller. 
3. also there was no response when touched on courses card or blogs card.

**FEEDBACK:**
Change the UI colour, made some parts of it responsive.

**_Describe the solution you'd like_**
1. So I changed the the colour from blue to duo combination of Black + Grey + neon green touch ,
4. changed the look of testimonials Carousel design. 
5. changed the way it responses,
6. also changed the courses section in website.

**_Describe alternatives you've considered_**
   No alternative methods simply editing CSS

**_Additional context_**
    I wasn't able to take screenshot of how website look before:

    [NOT AVAILALE]

    After:

https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/75314730/1229d5e4-7647-4789-bb47-843ec455518f

### PR DESCRIPTION
**Pull request by harsh11-11**
## What does this PR do?

This PR updates the colour of website, simply replicating dark mode, but some normal border designs added, then made main page, course sectio cards, testimonials responsive and it gives response when hover on it.

Fixes #156 

https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/75314730/a57e4d08-bf56-4ed2-871b-0da0e01d42b9

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Chore (refactoring code, technical debt, workflow improvements)
- New feature (non-breaking change which adds functionality)

## How should this be tested?

- [ ] Open the website
- [ ] You will see a whole screen dedicated to introduction.
- [ ] Now check its responsiveness by right clicking on it, and checking for all devices available through INSPECT option.
- [ ] Then scroll down you will see grey background on courses section. Also check its responsiveness.
- [ ] Then scroll down check TESTimonials section to made gap between each testimony. Applied boundary . Also check responsiveness thru INSPECT option. 

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by TheMohit2003** [comment]
@harsh11-11 , there is a merge conflict . [Watch](https://www.youtube.com/watch?v=l03tGz4pXoQ) this video to understand more on merge conflict

**Comment by TheMohit2003** [comment]
@harsh11-11 , if you don't install any new dependency , then do not commit your yarn.lock file . [Read](https://stackoverflow.com/a/40206145) this blog for better understanding.

**Comment by harsh11-11** [comment]
> @harsh11-11 , there is a merge conflict . [Watch](https://www.youtube.com/watch?v=l03tGz4pXoQ) this video to understand more on merge conflict

I have removed every conflict that was displaying on my screen.

**Comment by harsh11-11** [comment]
> @harsh11-11 , if you don't install any new dependency , then do not commit your yarn.lock file . [Read](https://stackoverflow.com/a/40206145) this blog for better understanding.

YES it was also in merge conflict and now I have pull the same yarn.lock file from OG repo and made the required changes and then pushed that for merge.

**Comment by harsh11-11** [comment]
SORRY but why my merge was closed is it not good code, should I pull request again.

**Comment by piyushgarg-dev** [comment]
Hi @harsh11-11, Thanks a lot for contributing, Please check https://github.com/piyushgarg-dev/piyushgargdev-nextjs/issues/156#issuecomment-1586164176

**Comment by harsh11-11** [comment]
> Hi @harsh11-11, Thanks a lot for contributing, Please check [#156 (comment)](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/issues/156#issuecomment-1586164176)

yes sir I saw your comment about colour scheme, i do respect your choices, but I have to say that I have also made website responsive

1. If you see this image down it is not responsive. (Original)
Screenshot 2023-06-11 at 8 13 26 PM

2. I have made responsive: (After my changes)
Screenshot 2023-06-11 at 8 15 34 PM

**Comment by harsh11-11** [comment]
> > Hi @harsh11-11, Thanks a lot for contributing, Please check [#156 (comment)](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/issues/156#issuecomment-1586164176)
> 
> yes sir I saw your comment about colour scheme, i do respect your choices, but I have to say that I have also made website responsive
> 
> 1. If you see this image down it is not responsive. (Original)
> 
> Screenshot 2023-06-11 at 8 13 26 PM
> 2. I have made responsive: (After my changes)
> 
> Screenshot 2023-06-11 at 8 15 34 PM

SO should create new issue about responsiveness.

**Pull request closed without merging**
