### PR TITLE
fix: Fix font size of Checkout-My-Interactive-Courses

### LINKED ISSUE #85: [enhancement] font-size of "Checkout My Interactive Courses" should increase
**Describe the bug**
In the cource section font -size of "Checkout My Interactive Courses" is small and less vigilent.

**To Reproduce**
1. Go to https://www.piyushgarg.dev/#
2. Scroll down to 'cources'
4. see checkout my cources

**Expected behavior**
font-size should be increased of "Checkout My Interactive Courses" and should be bold.

**Screenshots**
image

image

### PR DESCRIPTION
**Pull request by prajapatdip**
## What does this PR do?
Increase the font size of "Checkout My Interactive Courses"  of Courses section

Fixes #85

Screenshot from 2023-06-10 11-10-15

## Type of change

- New feature (non-breaking change which adds functionality)

## How should this be tested?

- [ ] Go to the Courses Section.
- [ ] Check the font size of "Checkout My Interactive Courses".

## Mandatory Tasks

- [X] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by TheMohit2003** [comment]
@prajapatdip , thank you for your contribution .

**Review by TheMohit2003 — CHANGES_REQUESTED** [review]
Please, remove yarn.lock from the commits.

**Comment by TheMohit2003** [comment]
The title "fix: Fix font size of Checkout-My-Interactive-Courses" has passed the test. This title indicates that the pull request is fixing an issue related to the font size in the Checkout-My-Interactive-Courses feature. By using the prefix "fix," it signifies that this pull request is aimed at resolving a bug or an error. The test was successful because it followed the required format specified in the error message and provided clear information about the nature of the change being made.  

Next time you open a PR, write its title in this format :   
**"[prefix]: Description of the change"**

**Review by TheMohit2003 — APPROVED** [review]

**Comment by prajapatdip** [comment]
Can I again make this PR after changing the title and removing the yarn.lock file?

**Pull request closed without merging**
