### PR TITLE
fix: spacing issue between text and subscribe button on home page

### LINKED ISSUE #111: Spacing issue between text and subscribe button
**Describe the bug**
when we go to piyushgarg.dev and scroll a bit we show youtube section their between subscribe button and text spacing issue, it have less margin bottom after the last "Thanks in advance!" text

**To Reproduce**
1. Go to 'piyushgarg.dev'
2. Scroll down to youtube section'
3. Spacing issue

**Expected behavior**
just add their some more margin or padding

**Screenshots**
Screenshot from 2023-06-09 16-09-59

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser chrome
 - Version 112.0.5615.165

### PR DESCRIPTION
**Pull request by VedP20**
What does this PR do?

fixes spacing issue between text and subscribe button on home page and also properly adjust the spacing between the heading and body text inside the services section of the home page

Fixes #111

Screenshot (175)

Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [X] Test A - Just navigate to the home page now you can see the proper spacing between the heading, body text and button

Mandatory Tasks

- [X] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by piyushgarg-dev** [comment]
Hey @VedP20, Thanks for contributing ❤️
I see that there are more commits coming in this PR, can you please remove them?

**Comment by VedP20** [comment]
Can you please let me know which part I need to remove?

**Comment by VedP20** [comment]
I tried to fix the the quote issue from single quote to double quote may be that's why you are seeing protfolio.jsx file

**Comment by VedP20** [comment]
Here is the new PR to fix this issue , Kindly check and let me know if there are any changes that I need the make.
Thank you 😊

**Pull request closed without merging**
