### PR TITLE
fix: alignment of discord button and Piyush's pic

### PR DESCRIPTION
**Pull request by mohibkay**
## What does this PR do?

Fixes #(#98)

image

https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/66241121/e1c61ce8-f070-47e4-8a33-a418854c8393

## Type of change

- Bug fix (non-breaking change which fixes alignment of the "Join Discord Button" and Piyush's Pic)

## How should this be tested?
Kindly visit the homepage to see the fix.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by TheMohit2003** [comment]
@mohibkay, that's great!

**Comment by simrin3308** [comment]
Hello @mohibkay. I have a suggestion. In smaller devices we can text align center.  We can also Keep the image on top and text div down. It will look more good.

**Comment by mohibkay** [comment]
Hey, @simrin3308, thank you for your suggestion. 
I have made the text center aligned in another PR as it was a different issue already created. 

Please take a look here: https://github.com/piyushgarg-dev/piyushgargdev-nextjs/pull/116

**Comment by mohibkay** [comment]
Please let me know if I should merge the changes in both the PRs and update them.

**Comment by TheMohit2003** [comment]
Hey @mohibkay , what do you think of @simrin3308 suggestion , It sounds great though . Can you fix it ?

**Comment by simrin3308** [comment]
@TheMohit2003 @mohibkay That image exactly catches my suggestion... This will look impressive if implemented.

**Comment by TheMohit2003** [comment]
@simrin3308 and @mohibkay , i guess this feature has been addressed in PR #38 .
[Here](https://piyushgargdev-nextjs-git-fork-bajaj2o-fix-sm-hero-ui-piyushgarg.vercel.app/) is the preview link

**Comment by mohibkay** [comment]
@TheMohit2003 okay cool then.

**Comment by simrin3308** [comment]
@TheMohit2003 looks impressive

**Comment by piyushgarg-dev** [comment]
Amazing PR ❤️

**Pull request merged**
