### PR TITLE
fix: spacing on the sub button with margin-top

### LINKED ISSUE #111: Spacing issue between text and subscribe button
**Describe the bug**
when we go to piyushgarg.dev and scroll a bit we show youtube section their between subscribe button and text spacing issue, it have less margin bottom after the last "Thanks in advance!" text

**To Reproduce**
1. Go to 'piyushgarg.dev'
2. Scroll down to youtube section'
3. Spacing issue

**Expected behavior**
just add their some more margin or padding

**Screenshots**
Screenshot from 2023-06-09 16-09-59

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser chrome
 - Version 112.0.5615.165

### PR DESCRIPTION
**Pull request by luckyklyist**
## What does this PR do?

Fixes #111 

image

### CODE REVIEW

**Review by TheMohit2003 — CHANGES_REQUESTED** [review]
Hey @luckyklyist , you have commited yarn.lock as well . Kindly remove that .

**Comment by luckyklyist** [comment]
> Hey @luckyklyist , you have commited yarn.lock as well . Kindly remove that .

sure

**Comment by luckyklyist** [comment]
@TheMohit2003  I have removed the yarn.lock file

**Comment by piyushgarg-dev** [comment]
Closing this PR in ref https://github.com/piyushgarg-dev/piyushgargdev-nextjs/pull/149

**Pull request closed without merging**
