### PR TITLE
feat: Added Contact Form on Homepage with Google Sheet API

### LINKED ISSUE #25: Add a Contact Me Form on HomePage
**Is your feature request related to a problem? Please describe.**
There is no Contact Me Form on the Page, There is no way for users to contact the owner and add a message to communicate with the site owner.

**Describe the solution you'd like**
Create a Contact Form on HomePage or on the Contact Us page. The Contact Us form should be connected to a backend using Vercel API Routes that can save the submissions to Google Sheets or any other free service.

**Describe alternatives you've considered**
There is an email ID given on the homepage which can be used to manually send an email to the site owner.

**Additional context**
Screenshot 2023-06-06 at 10 35 15 AM

### PR DESCRIPTION
**Pull request by luckyklyist**
## What does this PR do?

Fixes #25 
/claim #25

1. Utilized the google-spreadsheet npm package (version 3.3.0) to handle user form submissions.
2. Integrated Next.js' pages/api functionality to create an API route for form submission.
3. Extracted the form data from the request body, including fields such as Name, Email, and Message.
4. Loaded the Google Sheets document using the provided SPREAD_SHEET_ID environment variable.
5. Implemented authentication using the CLIENT_EMAIL and PRIVATE_KEY obtained from the Google Console.
6. Appended the form data as a new row in the Google Sheets document.
7. Handled success and error responses accordingly.
8. Implemented redirection to the home page after successful form submission.

image

[Screencast from 06-06-2023 05:07:49 PM.webm](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/35479077/5ae5ee28-d006-452d-b5ec-0051c8c397a9)

- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## To set up and use this feature, the following steps are required:

1. Obtain the CLIENT_EMAIL and PRIVATE_KEY from the Google Console.
2. Set the SPREAD_SHEET_ID environment variable to your specific Google Sheets document ID.
3. Make sure the Google Sheets document has a header row with columns for Name, Email, and Message fields.
4. Provide the necessary permissions to the CLIENT_EMAIL for accessing the Google Sheets document.

I would appreciate it if you could review my PR and provide any feedback or suggestions for improvement. Currently, I am working on the Vercel API and facing an error in the redirection part in the hompage. Your guidance in resolving this issue would be greatly appreciated.

## Updated video 

https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/35479077/d0458acc-8fee-47ef-8f36-4be4806a1cf8

### CODE REVIEW

**Comment by piyushgarg-dev** [comment]
Amazing PR + Description ✨

**Comment by piyushgarg-dev** [comment]
There are multiple commits in this PR.
Please remove commit https://github.com/piyushgarg-dev/piyushgargdev-nextjs/pull/40/commits/06b079d8c6ecfb3fd3a28495ee37c65deafa563b

**Comment by luckyklyist** [comment]
> There are multiple commits in this PR. Please remove commit [06b079d](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/commit/06b079d8c6ecfb3fd3a28495ee37c65deafa563b)

sure

**Comment by piyushgarg-dev** [comment]
Amazing, Please add the env variables that need to be added in `.env.example` file and then we are ready to merge.

**Pull request merged**
